import os

TELEGRAM_BOT_TOKEN = os.getenv("TELEGRAM_BOT_TOKEN")
TELEGRAM_CHANNEL_ID = os.getenv("TELEGRAM_CHANNEL_ID")

TELEGRAM_LINK_VIP = os.getenv("TELEGRAM_LINK_VIP")
TELEGRAM_LINK_SAIBA_MAIS = os.getenv("TELEGRAM_LINK_SAIBA_MAIS")

GOOGLE_DRIVE_NOVOS_FOLDER_ID = os.getenv("GOOGLE_DRIVE_NOVOS_FOLDER_ID")
GOOGLE_DRIVE_USADOS_FOLDER_ID = os.getenv("GOOGLE_DRIVE_USADOS_FOLDER_ID")
GOOGLE_SERVICE_ACCOUNT_JSON = os.getenv("GOOGLE_SERVICE_ACCOUNT_JSON")

INTERVALO_HORAS = int(os.getenv("INTERVALO_HORAS", "4"))
LIMITE_IMAGENS_RECENTES = int(os.getenv("LIMITE_IMAGENS_RECENTES", "80"))
QUANTIDADE_COLAGEM = int(os.getenv("QUANTIDADE_COLAGEM", "4"))
ROI_MINIMO = float(os.getenv("ROI_MINIMO", "30"))

PASTA_TEMP = "/tmp/bot_aviso_vip"
PASTA_PRINTS = f"{PASTA_TEMP}/prints"
PASTA_COLAGENS = f"{PASTA_TEMP}/colagens"